#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "code.h"
#include "parameters.h"

#define FIXTURE_COUNT 256
#define RM_BLOCK_BYTES (PARAM_N2 / 8)
#define MSG_WORDS CEIL_DIVIDE(PARAM_K, 8)

static uint32_t prng_state = 0x128c0de5u;

static void init_prng_from_env(void)
{
    const char *seed = getenv("HQC_FIXTURE_SEED");
    if (seed != NULL && seed[0] != '\0') {
        prng_state = (uint32_t)strtoul(seed, NULL, 0);
        if (prng_state == 0) {
            prng_state = 1;
        }
    }
}

static uint32_t prng_next(void)
{
    uint32_t x = prng_state;
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    prng_state = x;
    return x;
}

static void fill_message(uint8_t message[PARAM_K])
{
    for (size_t i = 0; i < PARAM_K; ++i) {
        message[i] = (uint8_t)prng_next();
    }
}

static void inject_symbol_errors(uint8_t codeword[VEC_N1N2_SIZE_BYTES], uint8_t errors)
{
    uint8_t used[PARAM_N1] = {0};

    for (uint8_t i = 0; i < errors; ++i) {
        size_t position;
        do {
            position = prng_next() % PARAM_N1;
        } while (used[position]);
        used[position] = 1;

        size_t offset = position * RM_BLOCK_BYTES;
        uint8_t mask = (uint8_t)(prng_next() | 1u);
        for (size_t j = 0; j < RM_BLOCK_BYTES; ++j) {
            codeword[offset + j] ^= (uint8_t)(mask + (uint8_t)(j * 17u));
        }
    }
}

static void print_array_1d(const char *name, const uint8_t *buf, size_t len)
{
    printf("const uint8_t %s[%zu] = {", name, len);

    for (size_t i = 0; i < len; ++i) {
        if (i % 12 == 0) {
            printf("\n    ");
        } else {
            printf(" ");
        }
        printf("0x%02x", buf[i]);
        if (i + 1 != len) {
            printf(",");
        }
    }
    printf("\n};\n\n");
}

static void print_array_2d(const char *name, const uint8_t *buf, size_t rows, size_t cols, int aligned)
{
    if (aligned) {
        printf("const uint8_t %s[%zu][%zu] __attribute__((aligned(128))) = {\n", name, rows, cols);
    } else {
        printf("const uint8_t %s[%zu][%zu] = {\n", name, rows, cols);
    }

    for (size_t r = 0; r < rows; ++r) {
        printf("    {");
        for (size_t c = 0; c < cols; ++c) {
            if (c % 12 == 0) {
                printf("\n        ");
            } else {
                printf(" ");
            }
            printf("0x%02x", buf[r * cols + c]);
            if (c + 1 != cols) {
                printf(",");
            }
        }
        printf("\n    }");
        if (r + 1 != rows) {
            printf(",");
        }
        printf("\n");
    }
    printf("};\n\n");
}

int main(void)
{
    init_prng_from_env();

    uint8_t messages[FIXTURE_COUNT][PARAM_K] = {{0}};
    uint8_t codewords[FIXTURE_COUNT][VEC_N1N2_SIZE_BYTES] = {{0}};
    uint8_t recovered_messages[FIXTURE_COUNT][PARAM_K] = {{0}};
    uint8_t rs_symbol_errors[FIXTURE_COUNT] = {0};

    for (size_t fixture = 0; fixture < FIXTURE_COUNT; ++fixture) {
        uint64_t message_words[MSG_WORDS] = {0};
        uint64_t recovered_words[MSG_WORDS] = {0};
        uint64_t codeword_words[VEC_N1N2_SIZE_64] = {0};
        uint8_t *message = (uint8_t *)message_words;
        uint8_t *recovered = (uint8_t *)recovered_words;
        uint8_t *codeword = (uint8_t *)codeword_words;

        fill_message(message);
        rs_symbol_errors[fixture] = (uint8_t)(fixture % (PARAM_DELTA + 1));

        code_encode(codeword_words, message_words);
        inject_symbol_errors(codeword, rs_symbol_errors[fixture]);
        code_decode(recovered_words, codeword_words);

        if (memcmp(message, recovered, PARAM_K) != 0) {
            fprintf(stderr, "ERROR: fixture %zu does not decode to expected message\n", fixture);
            return 1;
        }

        memcpy(messages[fixture], message, PARAM_K);
        memcpy(codewords[fixture], codeword, VEC_N1N2_SIZE_BYTES);
        memcpy(recovered_messages[fixture], recovered, PARAM_K);
    }

    printf("/* Generated by tools/gen_hqc1_decode_fixture.c. */\n");
    printf("#include \"hqc1_decode_fixture.h\"\n\n");
    print_array_2d("hqc1_fixture_messages", &messages[0][0], FIXTURE_COUNT, PARAM_K, 0);
    print_array_2d("hqc1_fixture_codewords", &codewords[0][0], FIXTURE_COUNT, VEC_N1N2_SIZE_BYTES, 1);
    print_array_2d("hqc1_fixture_expected_messages", &recovered_messages[0][0], FIXTURE_COUNT, PARAM_K, 0);
    print_array_1d("hqc1_fixture_rs_symbol_errors", rs_symbol_errors, FIXTURE_COUNT);

    return 0;
}
